### ISSUE TITLE
枠外をクリック、爆発時にクリックするとエラー / ２回押すと止まる

### ISSUE THREAD

**Issue by irimo** [irimo/takahashi-akashic#6]

**Comment by irimo** [comment]
engineFilesV3_2_3.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'unregister')
    at E.destroy (engineFilesV3_2_3.js:1:165278)
    at main.js:340:26
    at TimerIdentifier._handleElapse (engineFilesV3_2_3.js:1:141389)
    at Trigger.fire (engineFilesV3_2_3.js:1:439308)
    at Timer.tick (engineFilesV3_2_3.js:1:140037)
    at TimerManager._tick (engineFilesV3_2_3.js:1:143882)
    at Trigger.fire (engineFilesV3_2_3.js:1:439308)
    at Game.tick (engineFilesV3_2_3.js:1:69243)
    at GameLoop._onFrameNormal (engineFilesV3_2_3.js:1:249375)
    at GameLoop._onFrame (engineFilesV3_2_3.js:1:243790)

**Comment by irimo** [comment]
できたはず

**Comment by arigayas** [comment]
修正お疲れさまでした。
